# Generated by Django 3.1.7 on 2021-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('no_of_passengers', models.IntegerField(null=True)),
                ('travel_class', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
