# Generated by Django 3.1.7 on 2021-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_createdflights_createdtrains'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdflights',
            name='pricing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='createdtrains',
            name='pricing',
            field=models.IntegerField(null=True),
        ),
    ]
