# Generated by Django 3.1.7 on 2021-04-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210406_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.DeleteModel(
            name='Trains',
        ),
        migrations.AlterField(
            model_name='createdflights',
            name='pricing',
            field=models.CharField(max_length=100),
        ),
    ]
