# Generated by Django 3.1.7 on 2021-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_mybookedflights'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100000)),
                ('pricing', models.CharField(max_length=10000)),
                ('stay', models.CharField(max_length=1000)),
            ],
        ),
    ]
